@WebApiProject_HostAddress = https://localhost:7072

GET {{WebApiProject_HostAddress}}/todos/
Accept: application/json

###
GET {{WebApiProject_HostAddress}}/todos/1
Accept: application/json

###
POST {{WebApiProject_HostAddress}}/todos?title=abcd
Accept: application/json

###
PUT {{WebApiProject_HostAddress}}/todos
Accept: application/json
Content-Type: application/json

{
  "title": "iamtest",
  "description": "content"
}

###
DELETE {{WebApiProject_HostAddress}}/todos/8
Accept: application/json

###
DELETE {{WebApiProject_HostAddress}}/todos/purge
Accept: application/json